# Generated by Django 3.0.2 on 2020-01-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('default_time', models.IntegerField(default=3600)),
            ],
        ),
        migrations.CreateModel(
            name='TimerDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=32)),
                ('local_ip', models.CharField(max_length=32)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timerdashboard.Room')),
            ],
        ),
        migrations.CreateModel(
            name='TimerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TimerDeviceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_left', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timerdashboard.TimerDevice')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timerdashboard.TimerState')),
            ],
        ),
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Started on')),
                ('date_maxend', models.DateTimeField(verbose_name='End expected on')),
                ('date_finished', models.DateTimeField(verbose_name='Finished on')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timerdashboard.GameResult')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timerdashboard.Room')),
            ],
        ),
    ]
