# Generated by Django 3.0.2 on 2020-01-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='date_finished',
            field=models.DateTimeField(null=True, verbose_name='Finished on'),
        ),
    ]
