# Generated by Django 3.0.2 on 2020-01-03 18:24

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('timerdashboard', '0002_auto_20200103_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimerDevice',
            new_name='RoomDevice',
        ),
    ]
